version: "3"

services:
  wordpressdb:
    image: mysql:5.6
    restart: always
    volumes:
      - "./database:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    
  wordpress:
    depends_on:
      - wordpressdb
    image: wordpress:latest
    restart: always
    ports:
      - "8083:80"
    volumes:
      - "./webserver/var/log:/var/log"
      - "./webserver/var/www/html:/var/www/html"
    environment:
      WORDPRESS_DB_HOST: wordpressdb
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: user
      WORDPRESS_DB_NAME: wordpressdb
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: define( 'WP_DEBUG_LOG', true );

