version: "3"
    
services:
  wordpressdb:
    image: mysql:5.6
    volumes:
      - "./database:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    
  wordpress:
    depends_on:
      - wordpressdb
    image: wordpress:latest
    volumes:
      - "./webserver:/var/www/html"
    ports:
      - "8083:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: wordpressdb
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: user
      WORDPRESS_DB_NAME: wordpressdb

